[workspace]
authors = ["Matt Topol <matt@columnar.tech>"]
channels = ["conda-forge"]
name = "snowflake-build-demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
adbc-drivers = "dbc sync"
get-odbc = "./get_odbc.sh"

[dependencies]
uv = ">=0.9.2,<0.10"
python = "3.13.*"
r-base = ">=4.5.1,<4.6"
r-tibble = ">=3.3.0,<4"
unixodbc = ">=2.3.12,<3"
go = ">=1.25.2,<2"

[pypi-dependencies]
adbc-driver-manager = ">=1.8.0, <2"
pyarrow = ">=21.0.0, <22"
pyodbc = ">=5.2.0, <6"
polars = ">=1.34.0, <2"

[activation.env]
ODBCSYSINI = "$PIXI_PROJECT_ROOT"
ODBCINI = "$PIXI_PROJECT_ROOT/snowflake_odbc/conf/odbc.ini"
ODBCINSTINI = "snowflake_odbc/conf/odbcinst.ini"
PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
CGO_CFLAGS = "-I$CONDA_PREFIX/include"
CGO_LDFLAGS = "-L$CONDA_PREFIX/lib"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
